In [77]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [78]:
dataset = pd.read_csv('dummy_repair_data.csv')
X = dataset.iloc[:, :2].values
y = dataset[['Type of Repair'	,'Min Repair Cost (INR)',	'Max Repair Cost (INR)']]

In [79]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y['Type of Repair'] = le.fit_transform(y['Type of Repair'])

<ipython-input-79-ed54b718bbf5>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['Type of Repair'] = le.fit_transform(y['Type of Repair'])


In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [81]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [82]:
from sklearn.svm import SVC
from sklearn.multioutput import MultiOutputClassifier
classifier = MultiOutputClassifier(SVC(kernel = 'rbf',random_state = 0))
classifier.fit(X_train, y_train)

MultiOutputClassifier(estimator=SVC(random_state=0))

In [83]:
y_pred = classifier.predict(X_test)
for i in range(len(y_pred)):
    min_cost = y_pred[i, 1]
    max_cost = y_pred[i, 2]

    if max_cost < min_cost:
        y_pred[i, 1], y_pred[i, 2] = max_cost, min_cost
print(y_pred)

[[    1 20000 70000]
 [    1  5000 25000]
 [    1  5000 20000]
 [    1  5000 20000]
 [    0  5000 70000]
 [    2  5000 70000]
 [    2 25000 50000]
 [    2 20000 70000]
 [    1  5000 20000]
 [    2 25000 50000]
 [    2 20000 70000]
 [    2 20000 70000]
 [    2 20000 70000]
 [    2 20000 70000]
 [    1  5000 20000]
 [    1  5000 20000]
 [    2 20000 70000]
 [    1  5000 25000]
 [    2 25000 50000]
 [    2 20000 70000]]


In [84]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test['Type of Repair'],y_pred[:,0])

0.6

In [85]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test['Min Repair Cost (INR)'],y_pred[:,1])

0.3

In [86]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test['Max Repair Cost (INR)'],y_pred[:,2])

0.25

In [87]:
y_pred = pd.DataFrame(y_pred, columns=['Type of Repair'	,'Min Repair Cost (INR)',	'Max Repair Cost (INR)'])
y_pred['Type of Repair'] = le.inverse_transform(y_pred['Type of Repair'])

In [88]:
print(y_pred)

         Type of Repair  Min Repair Cost (INR)  Max Repair Cost (INR)
0         Minor repairs                  20000                  70000
1         Minor repairs                   5000                  25000
2         Minor repairs                   5000                  20000
3         Minor repairs                   5000                  20000
4        Major overhaul                   5000                  70000
5   Partial replacement                   5000                  70000
6   Partial replacement                  25000                  50000
7   Partial replacement                  20000                  70000
8         Minor repairs                   5000                  20000
9   Partial replacement                  25000                  50000
10  Partial replacement                  20000                  70000
11  Partial replacement                  20000                  70000
12  Partial replacement                  20000                  70000
13  Partial replacem